import {
  BookingActivityItem,
  MetricCardData,
  MentorAllocationItem,
  AvailableMentorQueueItem,
  DashboardVerificationSummary,
} from '@/types/dashboard.types';

export const DASHBOARD_METRICS: readonly MetricCardData[] = [
  {
    id: 'bookings',
    title: "Today's bookings",
    value: 7,
    subtext: 'Confirmed trial sessions',
    iconName: 'calendar',
    indicatorColor: '#00A86B',
  },
  {
    id: 'mentors',
    title: 'Mentors assigned',
    value: 5,
    total: 10,
    subtext: 'Active today across all tracks',
    iconName: 'users',
  },
  {
    id: 'classes',
    title: 'Classes today',
    value: 7,
    total: 20,
    subtext: 'System daily capacity max 20',
    iconName: 'pie',
  },
  {
    id: 'capacity',
    title: 'Available capacity',
    value: 13,
    subtext: 'Remaining demo slots today',
    iconName: 'zap',
  },
] as const;

export const SCHEDULING_ACTIVITIES: readonly BookingActivityItem[] = [
  {
    id: 'BK-1024',
    parentName: 'John Doe',
    parentEmail: 'john.doe@example.com',
    parentLocalTime: '10:00 AM',
    timezone: 'Europe/London',
    timezoneDetail: 'Europe/London (BST · UTC+1)',
    mentor: {
      id: 'mentor-07',
      code: '07',
      name: 'Ananya G.',
      track: 'CODING',
    },
    slotIst: '14:30 IST',
    status: 'Confirmed',
    classUrl: 'https://meet.codeyoung.com/trial/room-cy-1024',
  },
  {
    id: 'BK-1023',
    parentName: 'Sarah Miller',
    parentEmail: 'sarah.m@example.com',
    parentLocalTime: '04:30 PM',
    timezone: 'America/New_York',
    timezoneDetail: 'America/New_York (EDT · UTC-4)',
    mentor: {
      id: 'mentor-04',
      code: '04',
      name: 'Amitabh V.',
      track: 'MATH',
    },
    slotIst: '02:00 IST (+1)',
    status: 'Confirmed',
    classUrl: 'https://meet.codeyoung.com/trial/room-cy-1023',
  },
  {
    id: 'BK-1022',
    parentName: 'Rohan Mehta',
    parentEmail: 'rohan.m@example.com',
    parentLocalTime: '01:30 PM',
    timezone: 'Asia/Dubai',
    timezoneDetail: 'Asia/Dubai (GST · UTC+4)',
    mentor: {
      id: 'mentor-02',
      code: '02',
      name: 'Rahul K.',
      track: 'SCIENCE',
    },
    slotIst: '15:00 IST',
    status: 'Confirmed',
    classUrl: 'https://meet.codeyoung.com/trial/room-cy-1022',
  },
  {
    id: 'BK-1021',
    parentName: 'Emily Zhang',
    parentEmail: 'emily.z@outlook.com',
    parentLocalTime: '05:00 PM',
    timezone: 'Asia/Singapore',
    timezoneDetail: 'Asia/Singapore (SGT · UTC+8)',
    mentor: {
      id: 'mentor-01',
      code: '01',
      name: 'Deepa M.',
      track: 'ENGLISH',
    },
    slotIst: '14:30 IST',
    status: 'Confirmed',
    classUrl: 'https://meet.codeyoung.com/trial/room-cy-1021',
  },
  {
    id: 'BK-1020',
    parentName: "Liam O'Connor",
    parentEmail: 'liam.oc@eircom.net',
    parentLocalTime: '12:00 PM',
    timezone: 'Europe/Dublin',
    timezoneDetail: 'Europe/Dublin (IST · UTC+1)',
    mentor: {
      id: 'mentor-06',
      code: '06',
      name: 'Vikram P.',
      track: 'DEFAULT',
    },
    slotIst: '16:30 IST',
    status: 'Confirmed',
    classUrl: 'https://meet.codeyoung.com/trial/room-cy-1020',
  },
  {
    id: 'BK-1019',
    parentName: 'Marcus Vance',
    parentEmail: 'mvance@comcast.net',
    parentLocalTime: '07:00 AM',
    timezone: 'America/Chicago',
    timezoneDetail: 'America/Chicago (CDT · UTC-5)',
    mentor: {
      id: 'mentor-06',
      code: '06',
      name: 'Vikram P.',
      track: 'DEFAULT',
    },
    slotIst: '17:30 IST',
    status: 'Confirmed',
    classUrl: 'https://meet.codeyoung.com/trial/room-cy-1019',
  },
  {
    id: 'BK-1018',
    parentName: 'Fatima Al-Sayed',
    parentEmail: 'fatima.s@gmail.com',
    parentLocalTime: '08:30 AM',
    timezone: 'Asia/Riyadh',
    timezoneDetail: 'Asia/Riyadh (AST · UTC+3)',
    mentor: {
      id: 'mentor-02',
      code: '02',
      name: 'Rahul K.',
      track: 'SCIENCE',
    },
    slotIst: '11:00 IST',
    status: 'Confirmed',
    classUrl: 'https://meet.codeyoung.com/trial/room-cy-1018',
  },
] as const;

export const MENTOR_ALLOCATIONS: readonly MentorAllocationItem[] = [
  {
    mentorCode: 'Mentor 02',
    mentorName: 'Rahul K.',
    assignedCount: 2,
    maxCapacity: 2,
    isFull: true,
  },
  {
    mentorCode: 'Mentor 06',
    mentorName: 'Vikram P.',
    assignedCount: 2,
    maxCapacity: 2,
    isFull: true,
  },
  {
    mentorCode: 'Mentor 01',
    mentorName: 'Deepa M.',
    assignedCount: 1,
    maxCapacity: 2,
    isFull: false,
  },
  {
    mentorCode: 'Mentor 04',
    mentorName: 'Amitabh V.',
    assignedCount: 1,
    maxCapacity: 2,
    isFull: false,
  },
  {
    mentorCode: 'Mentor 07',
    mentorName: 'Ananya G.',
    assignedCount: 1,
    maxCapacity: 2,
    isFull: false,
  },
] as const;

export const NEXT_AVAILABLE_MENTORS: readonly AvailableMentorQueueItem[] = [
  {
    mentorCode: 'Mentor 03',
    mentorName: 'Tanvi B.',
    assignedCount: 0,
    maxCapacity: 2,
  },
  {
    mentorCode: 'Mentor 05',
    mentorName: 'Karan S.',
    assignedCount: 0,
    maxCapacity: 2,
  },
  {
    mentorCode: 'Mentor 08',
    mentorName: 'Naveen R.',
    assignedCount: 0,
    maxCapacity: 2,
  },
  {
    mentorCode: 'Mentor 09',
    mentorName: 'Pooja S.',
    assignedCount: 0,
    maxCapacity: 2,
  },
  {
    mentorCode: 'Mentor 10',
    mentorName: 'Aditya N.',
    assignedCount: 0,
    maxCapacity: 2,
  },
] as const;


export const VERIFICATION_SUMMARY: DashboardVerificationSummary = {
  seededMentorsCount: 10,
  dailyCapPerMentor: 2,
  allocationStrategy: 'Least-booked mentor deterministic allocation',
  dbConstraint: 'PostgreSQL exclusion constraint on tstzrange / MongoDB transactional lock',
};
