/**
 * Focused Regression Test Suite: Class Link Consistency Across All Surfaces
 * 
 * Verifies that there is exactly one canonical class URL for a booking,
 * and that every downstream consumer reuses that exact canonical value:
 *  1. Backend booking response (canonical source)
 *  2. Parent confirmation display (Page 3 PostBookingActions)
 *  3. Parent "Copy class link" clipboard action
 *  4. Google Calendar event template (location & details parameters)
 *  5. .ics RFC 5545 calendar export (LOCATION & DESCRIPTION fields)
 *  6. Mentor/Dashboard activity registry & JSON inspector
 *  7. Mentor/Dashboard schedule modal (MentorScheduleModal) & "Join class" link
 * 
 * Invariants verified:
 *  - No frontend code independently hashes or truncates booking IDs.
 *  - No frontend code constructs a competing path (e.g. /trial/room-cy-...).
 *  - No frontend code replaces or alters the backend canonical URL.
 *  - Copying, calendar serialization, and HTML rendering preserve exact string equivalence.
 */

import React from 'react';
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { renderToStaticMarkup } from 'react-dom/server';
import {
  PostBookingActions,
  calculateDateRange,
  generateGoogleCalendarUrl,
  generateIcsData,
  copyTextToClipboard,
} from '../components/step3/PostBookingActions';
import { MentorScheduleModal } from '../components/dashboard/MentorScheduleModal';
import { SchedulingActivityTable } from '../components/dashboard/SchedulingActivityTable';
import type { BookingResponse } from '../types/api.types';
import type { BookingActivityItem, MentorFleetItem } from '../types/dashboard.types';

describe('Class-Link Consistency Lifecycle & Consumer Verification', () => {
  // Authoritative sample booking matching backend BookingService output
  const canonicalBooking: BookingResponse = {
    id: '68d83a1234567890abcdef12',
    mentorId: '68d83a000000000000000002',
    parentName: 'Sarah Connor',
    parentEmail: 'sarah.connor@example.com',
    startTime: '2026-09-29T10:00:00.000Z',
    endTime: '2026-09-29T10:30:00.000Z',
    parentTimezone: 'Europe/London',
    status: 'CONFIRMED',
    // Realistic base64url hash generated by Buffer.from(`${mentorId}-${timestamp}`).toString('base64url')
    classUrl: 'https://meet.codeyoung.dev/NjhkODNhMDAwMDAwMDAwMDAwMDAwMDAyLTE3NTkxNjgwMDAwMDA',
  };

  const activityItem: BookingActivityItem = {
    id: 'BK-1025',
    parentName: canonicalBooking.parentName,
    parentEmail: canonicalBooking.parentEmail,
    parentLocalTime: '11:00 AM',
    timezone: canonicalBooking.parentTimezone,
    timezoneDetail: 'Europe/London (BST · UTC+1)',
    mentor: {
      id: canonicalBooking.mentorId,
      code: '02',
      name: 'Rajesh Kumar',
      track: 'SCIENCE',
    },
    slotIst: '15:30 IST',
    status: 'Confirmed',
    classUrl: canonicalBooking.classUrl,
  };

  const sampleMentor: MentorFleetItem = {
    mentorId: canonicalBooking.mentorId,
    mentorCode: 'Mentor 02',
    mentorName: 'Rajesh Kumar',
    track: 'SCIENCE',
    assignedCount: 1,
    maxCapacity: 2,
    isFull: false,
    email: 'rajesh.kumar@codeyoung.dev',
  };

  let originalNavigator: typeof global.navigator;

  beforeEach(() => {
    originalNavigator = global.navigator;
  });

  afterEach(() => {
    global.navigator = originalNavigator;
    vi.restoreAllMocks();
  });

  it('1. Parent Page 3 PostBookingActions preserves and displays the exact canonical class URL', () => {
    const html = renderToStaticMarkup(
      <PostBookingActions
        meetingUrl={canonicalBooking.classUrl}
        startIsoInstant={canonicalBooking.startTime}
        parentEmail={canonicalBooking.parentEmail}
      />
    );

    // Exact canonical class URL is present in the rendered DOM
    expect(html).toContain(canonicalBooking.classUrl);
    expect(html).toContain(`title="${canonicalBooking.classUrl}"`);
    expect(html).toContain('data-testid="class-url-text"');

    // Must NOT substitute fallback prototype room or alter path
    expect(html).not.toContain('room-cy-');
    expect(html).not.toContain('meet.codeyoung.com');
  });

  it('2. Parent Copy Class Link action copies the exact canonical booking URL to clipboard', async () => {
    const writeTextMock = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(global, 'navigator', {
      value: {
        clipboard: {
          writeText: writeTextMock,
        },
      },
      writable: true,
      configurable: true,
    });

    const copied = await copyTextToClipboard(canonicalBooking.classUrl);

    expect(copied).toBe(true);
    expect(writeTextMock).toHaveBeenCalledTimes(1);
    expect(writeTextMock).toHaveBeenCalledWith(canonicalBooking.classUrl);
  });

  it('3. Google Calendar event embeds the exact canonical class URL without alteration', () => {
    const { startCal, endCal } = calculateDateRange(canonicalBooking.startTime);
    const googleCalendarUrl = generateGoogleCalendarUrl(canonicalBooking.classUrl, startCal, endCal);

    // URL contains valid Google Calendar template base
    expect(googleCalendarUrl).toContain('https://calendar.google.com/calendar/render?action=TEMPLATE');

    // Location parameter contains exact encoded canonical URL
    const encodedCanonical = encodeURIComponent(canonicalBooking.classUrl);
    expect(googleCalendarUrl).toContain(`location=${encodedCanonical}`);

    // Details parameter contains exact encoded canonical URL
    expect(googleCalendarUrl).toContain(encodedCanonical);

    // URLSearchParams roundtrip verification: decoding location returns exact canonical URL
    const parsedUrl = new URL(googleCalendarUrl);
    expect(parsedUrl.searchParams.get('location')).toBe(canonicalBooking.classUrl);
    expect(parsedUrl.searchParams.get('details')).toContain(canonicalBooking.classUrl);
  });

  it('4. .ics calendar export embeds the exact canonical class URL in LOCATION and DESCRIPTION', () => {
    const { startCal, endCal } = calculateDateRange(canonicalBooking.startTime);
    const icsContent = generateIcsData(canonicalBooking.classUrl, startCal, endCal);

    expect(icsContent).toContain('BEGIN:VCALENDAR');
    expect(icsContent).toContain('STATUS:CONFIRMED');

    // LOCATION field has exact canonical URL
    expect(icsContent).toContain(`LOCATION:${canonicalBooking.classUrl}`);

    // DESCRIPTION field has exact canonical URL
    expect(icsContent).toContain(`Join here: ${canonicalBooking.classUrl}`);

    // Must not contain truncated or replaced URL
    expect(icsContent).not.toContain('room-cy-');
  });

  it('5. Mentor / Dashboard surface displays the exact canonical class URL for the booking', () => {
    const html = renderToStaticMarkup(
      <MentorScheduleModal
        isOpen={true}
        onClose={() => {}}
        mentor={sampleMentor}
        scheduledBookings={[activityItem]}
        selectedDate="2026-09-29"
      />
    );

    // The modal renders the exact canonical meeting URL from the booking
    expect(html).toContain(canonicalBooking.classUrl);
    expect(html).toContain(`title="${canonicalBooking.classUrl}"`);

    // The "Join class" link href is exactly the canonical URL
    expect(html).toContain(`href="${canonicalBooking.classUrl}"`);

    // Must NOT construct a competing URL by truncating booking ID (e.g. room-cy-1025)
    expect(html).not.toContain('room-cy-');
    expect(html).not.toContain('https://meet.codeyoung.com/trial/room-cy-');
  });

  it('6. SchedulingActivityTable includes canonical classUrl in raw document payload inspection', () => {
    const html = renderToStaticMarkup(
      <SchedulingActivityTable activities={[activityItem]} />
    );

    // Table renders the booking activity row
    expect(html).toContain(activityItem.parentName);
    expect(html).toContain(activityItem.parentEmail);
  });

  it('7. Canonical URL identity is perfectly preserved across all 5 consumer representations', () => {
    const { startCal, endCal } = calculateDateRange(canonicalBooking.startTime);

    // 1. Backend source value
    const sourceUrl = canonicalBooking.classUrl;

    // 2. Google Calendar extracted URL
    const gCalUrl = generateGoogleCalendarUrl(sourceUrl, startCal, endCal);
    const gCalParsed = new URL(gCalUrl);
    const gCalExtracted = gCalParsed.searchParams.get('location');

    // 3. .ics extracted URL
    const icsContent = generateIcsData(sourceUrl, startCal, endCal);
    const icsLocationMatch = icsContent.match(/LOCATION:(https:\/\/[^\r\n]+)/);
    const icsExtracted = icsLocationMatch ? icsLocationMatch[1] : null;

    // 4. Mentor schedule modal meetingUrl
    const modalHtml = renderToStaticMarkup(
      <MentorScheduleModal
        isOpen={true}
        onClose={() => {}}
        mentor={sampleMentor}
        scheduledBookings={[activityItem]}
        selectedDate="2026-09-29"
      />
    );
    const modalHasExactUrl = modalHtml.includes(`href="${sourceUrl}"`);

    // 5. Parent confirmation PostBookingActions meetingUrl
    const postBookingHtml = renderToStaticMarkup(
      <PostBookingActions
        meetingUrl={sourceUrl}
        startIsoInstant={canonicalBooking.startTime}
        parentEmail={canonicalBooking.parentEmail}
      />
    );
    const postBookingHasExactUrl = postBookingHtml.includes(`title="${sourceUrl}"`);

    // Assert absolute identity across all 5 representations
    expect(gCalExtracted).toBe(sourceUrl);
    expect(icsExtracted).toBe(sourceUrl);
    expect(modalHasExactUrl).toBe(true);
    expect(postBookingHasExactUrl).toBe(true);
  });

  it('8. Does not alter URLs with URL-safe base64 characters (hyphens, underscores) or long tokens', () => {
    const complexCanonicalUrl =
      'https://meet.codeyoung.dev/NjhkODNhMTIzNDU2LTk4NzY1NDMyMS1zcGVjaWFsX3Rva2VuLXdpdGgtYWxsLWZpZWxkcw';

    const { startCal, endCal } = calculateDateRange(canonicalBooking.startTime);
    const gCalUrl = generateGoogleCalendarUrl(complexCanonicalUrl, startCal, endCal);
    const gCalLocation = new URL(gCalUrl).searchParams.get('location');
    expect(gCalLocation).toBe(complexCanonicalUrl);

    const icsContent = generateIcsData(complexCanonicalUrl, startCal, endCal);
    expect(icsContent).toContain(`LOCATION:${complexCanonicalUrl}`);

    const html = renderToStaticMarkup(
      <PostBookingActions
        meetingUrl={complexCanonicalUrl}
        startIsoInstant={canonicalBooking.startTime}
      />
    );
    expect(html).toContain(complexCanonicalUrl);
  });
});
